image: "dev.gitlab.org:5005/gitlab/gitlab-build-images:ruby-2.3-git-2.7-phantomjs-2.1"

stages:
  - test
  - deploy
  - automation
  - release

cache:
  key: "ruby-231"
  paths:
    - vendor/ruby

before_script:
  - bundle install --jobs=$(nproc) --retry=3 --path=vendor

rubocop:
  stage: test
  except:
    - triggers
  script:
    - bundle exec rubocop

specs:
  stage: test
  except:
    - triggers
  retry: 1
  script:
    - cp .env.example .env
    - git config --global user.email "you@example.com"
    - git config --global user.name "Your Name"
    - bundle exec rake
  artifacts:
    paths:
      - coverage/assets
      - coverage/index.html

pages:
  stage: deploy
  before_script: []
  script:
    - mkdir -p public/
    - mv coverage/ public/
  dependencies:
    - specs
  artifacts:
    paths:
      - public/
  only:
    - master
  except:
    - schedules

upstream-merge:
  stage: automation
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$AUTO_UPSTREAM_MERGE_BOT_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - git config --global user.email "gitlab-bot@gitlab.com"
    - git config --global user.name "GitLab Bot"
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
    - bundle exec rake upstream_merge
  only:
    - schedules

release:
  stage: release
  only:
    - triggers
  script:
    # Guard
    - if [ -z "${RELEASE_VERSION}" ]; then echo "$RELEASE_VERSION required!" && exit 1; fi

    # - Configure Git
    - git config --global user.email "robert+release-tools@gitlab.com"
    - git config --global user.name "GitLab Release Tools Bot"

    # - Set up our private SSH key for pushing to the necessary repositories
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$RELEASE_BOT_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts

    # - Configure API tokens
    - export GITLAB_API_PRIVATE_TOKEN="$RELEASE_BOT_PRODUCTION_TOKEN"
    - export DEV_API_PRIVATE_TOKEN="$RELEASE_BOT_DEV_TOKEN"

    # - Ship it!
    - bundle exec rake "release[$RELEASE_VERSION]"
