image: "dev.gitlab.org:5005/gitlab/gitlab-build-images:ruby-2.3-git-2.7-phantomjs-2.1"

cache:
  key: "ruby-231"
  paths:
  - vendor/ruby

rubocop:
  stage: test
  script:
    - which ruby
    - ruby -v
    - gem install bundler --no-ri --no-rdoc
    - bundle install --jobs $(nproc) "${FLAGS[@]}"
    - bundle exec rubocop

specs:
  stage: test
  script:
    - apt-get update -yqqq
    - apt-get install -yqqq --force-yes cmake
    - which ruby
    - ruby -v
    - gem install bundler --no-ri --no-rdoc
    - bundle install --jobs $(nproc) "${FLAGS[@]}"
    - cp .env.example .env
    - git config --global user.email "you@example.com"
    - git config --global user.name "Your Name"
    - bundle exec rake
  artifacts:
    paths:
      - coverage/assets
      - coverage/index.html

pages:
  stage: deploy
  script:
    - mkdir -p public/
    - mv coverage/ public/
  dependencies:
    - specs
  artifacts:
    paths:
      - public/
  only:
    - master
