image: "dev.gitlab.org:5005/gitlab/gitlab-build-images:release-tools"

stages:
  - test
  - deploy
  - automation
  - chatops

cache: &global-cache
  key: "ruby-25"
  paths:
    - vendor/ruby

# templates -------------------------------------------------------------------

.with-bundle: &with-bundle
  before_script:
    - bundle install --jobs=$(nproc) --retry=3 --path=vendor

# test ------------------------------------------------------------------------

dependency_scanning:
  image: docker:stable
  variables:
    DOCKER_DRIVER: overlay2
  allow_failure: true
  tags: []
  before_script: []
  cache: {}
  dependencies: []
  services:
    - docker:stable-dind
  script:
    - export SP_VERSION=$(echo "$CI_SERVER_VERSION" | sed 's/^\([0-9]*\)\.\([0-9]*\).*/\1-\2-stable/')
    - docker run
        --env DEP_SCAN_DISABLE_REMOTE_CHECKS="${DEP_SCAN_DISABLE_REMOTE_CHECKS:-false}"
        --volume "$PWD:/code"
        --volume /var/run/docker.sock:/var/run/docker.sock
        "registry.gitlab.com/gitlab-org/security-products/dependency-scanning:$SP_VERSION" /code
  artifacts:
    paths: [gl-dependency-scanning-report.json]
  except:
    - schedules
    - triggers

rubocop:
  <<: *with-bundle
  stage: test
  except:
    - schedules
    - triggers
  script:
    - bundle exec rubocop

specs:
  <<: *with-bundle
  stage: test
  except:
    - schedules
    - triggers
  retry: 1
  script:
    - cp .env.example .env
    - git config --global user.email "you@example.com"
    - git config --global user.name "Your Name"
    - bundle exec rspec
  artifacts:
    paths:
      - coverage/assets
      - coverage/index.html

# deploy ----------------------------------------------------------------------

pages:
  stage: deploy
  script:
    - mkdir -p public/
    - mv coverage/ public/
  dependencies:
    - specs
  artifacts:
    paths:
      - public/
  only:
    - master
  except:
    - schedules
    - triggers

# automation ------------------------------------------------------------------

release-managers:
  <<: *with-bundle
  stage: automation
  script:
    - source scripts/setup_ssh.sh
    - echo "$RELEASE_BOT_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - export GITLAB_API_PRIVATE_TOKEN="$RELEASE_BOT_PRODUCTION_TOKEN"
    - export DEV_API_PRIVATE_TOKEN="$RELEASE_BOT_DEV_TOKEN"
    - export OPS_API_PRIVATE_TOKEN="$RELEASE_BOT_OPS_TOKEN"
    - bundle exec rake release_managers:sync
  only:
    refs:
      - schedules
    variables:
      - $RELEASE_MANAGERS
  cache:
    <<: *global-cache
    policy: pull

upstream-merge:
  <<: *with-bundle
  stage: automation
  script:
    - source scripts/setup_ssh.sh
    - echo "$AUTO_UPSTREAM_MERGE_BOT_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - git config --global user.email "gitlab-bot@gitlab.com"
    - git config --global user.name "GitLab Bot"
    - bundle exec rake upstream_merge
  only:
    refs:
      - schedules
    variables:
      - $UPSTREAM_MERGE
  cache:
    <<: *global-cache
    policy: pull

feature-freeze:
  <<: *with-bundle
  stage: automation
  script:
    - bundle exec rake freeze
  only:
    refs:
      - schedules
    variables:
      - $FEATURE_FREEZE_WEBHOOK_URL

close-expired-qa-issues:
  <<: *with-bundle
  stage: automation
  script:
    - bundle exec rake close_expired_qa_issues
  only:
    refs:
      - schedules
    variables:
      - $CLOSE_EXPIRED_QA_ISSUES

validate-security-merge-requests:
  <<: *with-bundle
  stage: automation
  script:
    - bundle exec rake security:validate
  only:
    refs:
      - schedules
    variables:
      - $VALIDATE_SECURITY_MERGE_REQUESTS

auto-deploy:prepare:
  <<: *with-bundle
  stage: automation
  script:
    - bundle exec rake 'auto_deploy:prepare'
  only:
    refs:
      - schedules
    variables:
      - $CREATE_AUTO_DEPLOY_BRANCH_SCHEDULE == "true"

auto-deploy:pick:
  <<: *with-bundle
  stage: automation
  script:
    - bundle exec rake 'auto_deploy:pick'
  only:
    variables:
      - $CHERRY_PICK_AUTO_DEPLOY_BRANCH_SCHEDULE == "true"

auto-deploy:trigger:
  <<: *with-bundle
  stage: automation
  script:
    - bundle exec rake "passing_build:ee[$AUTO_DEPLOY_BRANCH,true]"
  only:
    variables:
      - $PASSING_BUILD_AUTO_DEPLOY_SCHEDULE == "true"

# chatops ---------------------------------------------------------------------

chatops:
  <<: *with-bundle
  stage: chatops
  script:
    - source scripts/setup_ssh.sh
    - echo "$RELEASE_BOT_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - git config --global user.email "robert+release-tools@gitlab.com"
    - git config --global user.name "GitLab Release Tools Bot"
    - ./bin/chatops $TASK
  only:
    - triggers
  cache:
    <<: *global-cache
    policy: pull

# nightly green master builds -------------------------------------------------

ee-green-master-build-trigger:
  <<: *with-bundle
  stage: automation
  script:
    - bundle exec rake 'passing_build:ee[master, true]'
  only:
    variables:
      - $EE_GREEN_MASTER_BUILD_TRIGGER == "true"

ce-green-master-build-trigger:
  <<: *with-bundle
  stage: automation
  script:
    - bundle exec rake 'passing_build:ce[master, true]'
  only:
    variables:
      - $CE_GREEN_MASTER_BUILD_TRIGGER == "true"
