inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  DisplayStyleGuide: false
  Exclude:
    - Rakefile
    - 'vendor/**/*'

# Gems in consecutive lines should be alphabetically sorted
Bundler/OrderedGems:
  Enabled: false

# Layout ######################################################################

Layout/MultilineMethodCallIndentation:
  Enabled: false

# Metrics #####################################################################

Metrics/BlockLength:
  Max: 82
  Exclude:
    - Rakefile
    - 'lib/tasks/**/*.rake'
    - 'spec/**/*_spec.rb'

# TODO: Enable
Metrics/LineLength:
  Enabled: false
  IgnoreCopDirectives: true
  Max: 120

# Naming ######################################################################

Naming/HeredocDelimiterNaming:
  Enabled: false

Naming/RescuedExceptionsVariableName:
  PreferredName: ex

Naming/UncommunicativeMethodParamName:
  MinNameLength: 2

# RSpec #######################################################################

RSpec/ContextWording:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

RSpec/SubjectStub:
  Enabled: false

# Style #######################################################################

Style/CommentAnnotation:
  Enabled: false

Style/Documentation:
  Enabled: false

# This often interferes with MaxLineLength, and we care about that more.
Style/IfUnlessModifier:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

# Maybe the most pedanitc cop there is?
Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Exclude:
    - Rakefile
    - 'lib/tasks/**/*.rake'
