# This file controls who has access to groups required to be a Release Manager
#
# The format should be as follows:
#
#   Your Name:
#     gitlab.com: your-gitlab-com-username
#     gitlab.org: your-dev-gitlab-org-username
#
# The only required key is `gitlab.com`; the other value will fall back to that
# if omitted.
#
# Try to maintain alphabetical order.

Alex Hanselka:
  gitlab.com: ahanselka
  gitlab.org: alex

Cindy Pallares:
  gitlab.com: cpallares

Diana Stanley:
  gitlab.com: dstanley

GitLab Release Tools Bot:
  gitlab.com: gitlab-release-tools-bot

Julius Kvedaras:
  gitlab.com: mrjkc
  gitlab.org: jkvedaras

James Lopez:
  gitlab.com: jameslopez
  gitlab.org: james

Jan Provaznik:
  gitlab.com: jprovaznik

Jose Vargas:
  gitlab.com: jivanvl
  gitlab.org: jvargas

Marin Jankovski:
  gitlab.com: marin

Robert Speicher:
  gitlab.com: rspeicher

Steve Azzopardi:
  gitlab.com: SteveAzz
  gitlab.org: sazzopardi

Thiago Presa:
  gitlab.com: tpresa
